import NlpTests.Core
import NlpTests.Pipeline
import NlpTests.Syntax
import NlpTests.Grammar
import NlpTests.Parse
import NlpTests.Sequence
import NlpTests.IO
import NlpTests.Eval
import NlpTests.EvalLemmas
import NlpTests.Eval.Evalb
import NlpTests.Integration
