import NlpTests.Core
import NlpTests.Pattern
import NlpTests.Pipeline
import NlpTests.Syntax
import NlpTests.Grammar
import NlpTests.Parse
import NlpTests.Sequence
import NlpTests.Dependency
import NlpTests.Tokenize
import NlpTests.Morphology
import NlpTests.Normalize
import NlpTests.IO
import NlpTests.Eval
import NlpTests.Eval.Dependency
import NlpTests.EvalLemmas
import NlpTests.Eval.Evalb
import NlpTests.Integration
import NlpTests.Readme
