import NlpTests.Pipeline.Ann
import NlpTests.Pipeline.Laws
import NlpTests.Pipeline.Effects
import NlpTests.Pipeline.Files
import NlpTests.Pipeline.Parallel
import NlpTests.Pipeline.Annotate
import NlpTests.Pipeline.Tokenize
import NlpTests.Pipeline.Morphology
import NlpTests.Pipeline.Corpora
import NlpTests.Pipeline.Parse
import NlpTests.Pipeline.Viterbi
import NlpTests.Pipeline.Evalb
