import NlpTests.Pipeline.Ann
import NlpTests.Pipeline.Laws
import NlpTests.Pipeline.Effects
import NlpTests.Pipeline.Files
import NlpTests.Pipeline.Parallel
import NlpTests.Pipeline.Annotate
import NlpTests.Pipeline.Tokenize
import NlpTests.Pipeline.Morphology
import NlpTests.Pipeline.Pos
import NlpTests.Pipeline.English
import NlpTests.Pipeline.Corpora
import NlpTests.Pipeline.Parse
import NlpTests.Pipeline.Viterbi
import NlpTests.Pipeline.Unary
import NlpTests.Pipeline.Constituency
import NlpTests.Pipeline.Dependency
import NlpTests.Pipeline.NonprojectiveDependency
import NlpTests.Pipeline.EnhancedDependency
import NlpTests.Pipeline.Ner
import NlpTests.Pipeline.RegexNer
import NlpTests.Pipeline.Evalb
