import Nlp.Core.Algebra.FreeSorted
import Nlp.Grammar.CFG

/-!
# Context-free derivations as free sorted terms

Each position in `CFG.prods` is a distinct generator. Consequently duplicate productions remain
distinct derivations, while the nonterminal input sorts make ill-typed rule composition
unrepresentable. Terminal literals stay on their production generator and are interpreted by the
yield fold.
-/

namespace Nlp

namespace Rule

/-- Nonterminal occurrences in a production's right-hand side, in source order. -/
def ntInputs (rule : Rule K) : List NT :=
  rule.rhs.toList.filterMap fun symbol ↦
    match symbol with
    | .nt nonterminal => some nonterminal
    | .tm _ => none

end Rule

namespace CFG

/-- A positional production generator. Equal production values at different slots stay distinct. -/
abbrev RuleId (grammar : CFG K) := Fin grammar.prods.size

/-- Retrieve the production named by a positional generator. -/
@[inline] def ruleAt (grammar : CFG K) (source : grammar.RuleId) : Rule K :=
  grammar.prods[source]

/-- The many-sorted signature generated by the positions in a CFG's production array. -/
def signature (grammar : CFG K) : FreeSorted.Signature NT where
  Gen := grammar.RuleId
  output source := (grammar.ruleAt source).lhs
  inputs source := (grammar.ruleAt source).ntInputs

/-- A finite, production-identity-preserving derivation rooted at `lhs`. -/
abbrev Deriv (grammar : CFG K) (lhs : NT) := FreeSorted.Term grammar.signature lhs

namespace Deriv

variable {K : Type} {grammar : CFG K} {lhs : NT}

private def appendYield :
    (symbols : List Sym) →
      FreeSorted.Values (fun _ : NT ↦ List Tok)
        (symbols.filterMap fun symbol ↦
          match symbol with
          | .nt nonterminal => some nonterminal
          | .tm _ => none) →
      List Tok
  | [], .nil => []
  | .tm token :: symbols, values => token :: appendYield symbols values
  | .nt _ :: symbols, .cons child children => child ++ appendYield symbols children

private def yieldAlgebra (grammar : CFG K) : FreeSorted.Algebra grammar.signature where
  Carrier := fun _ ↦ List Tok
  op source children :=
    appendYield (grammar.ruleAt source).rhs.toList (by
      simpa [signature, Rule.ntInputs] using children)

/-- Terminal yield of a CFG derivation, including literals interleaved around child derivations. -/
def yield (derivation : grammar.Deriv lhs) : List Tok :=
  FreeSorted.Term.fold (yieldAlgebra grammar) derivation

private def multiplyValues [Mul K] :
    {sorts : List NT} → FreeSorted.Values (fun _ : NT ↦ K) sorts → K → K
  | [], .nil, total => total
  | _ :: _, .cons value values, total => multiplyValues values (total * value)

private def weightAlgebra [Mul K] (grammar : CFG K) : FreeSorted.Algebra grammar.signature where
  Carrier := fun _ ↦ K
  op source children := multiplyValues children (grammar.ruleAt source).w

/--
Left-associated derivation weight: production weight followed by child weights in source order.

No multiplication law is required; the bracketing exactly matches the operational dynamic
programming kernels.
-/
def weight [Mul K] (derivation : grammar.Deriv lhs) : K :=
  FreeSorted.Term.fold (weightAlgebra grammar) derivation

end Deriv

/-- The language generated from `lhs`, expressed through finite free derivations. -/
def Yields (grammar : CFG K) (lhs : NT) (tokens : List Tok) : Prop :=
  ∃ derivation : grammar.Deriv lhs, derivation.yield = tokens

end CFG

end Nlp
